classdef MotorsPage < scanimage.guis.configuration.ConfigurationPage
    
    properties
        hMotorPanel;
        hNoSelText;
        hMotorList;
        hDimensionTable;
        hRemove;
        
        motors;
    end
    
    properties (SetObservable)
        mtrChoices = {};
        controllerType = '';
        
        comChoices = {};
        comPort = '';
        
        additionalParams;
        shortVelocity;
        longVelocity;
        moveCompleteDelay;
        
        motorList = {};
    end
    
    properties (Constant)
        modelClass = 'scanimage.components.Motors';
    end
    
    methods
        function obj = MotorsPage(hConfigEditor, create)
            if nargin < 2 || isempty(create)
                create = false;
            end
            obj = obj@scanimage.guis.configuration.ConfigurationPage(hConfigEditor,create);
            
            obj.listLabel = 'Stage Controllers (Motors)';
            obj.heading = 'Motors';
            obj.descriptionText = 'Configure stage controllers to enable view and control of the stage position in ScanImage. Multiple motors can be configured with physical axes mapped to the ScanImage XYZ coordinate system.';
            
            ph = 770;
            obj.hPanel = uipanel('parent',[],'BorderType','none','units','pixels','position',[0 0 990 ph]);
        
            uicontrol('parent', obj.hPanel, ...
                'Style', 'text', ...
                'HorizontalAlignment', 'left', ...
                'String', 'Configured Motor Controllers', ...
                'fontsize',10,...
                'Units', 'pixels', ...
                'Position', [46 ph-44 200 16]);
            
            obj.hMotorList = most.gui.uicontrol('parent', obj.hPanel, ...
                'Style', 'listbox', ...
                'Units', 'pixels', ...
                'callback',@obj.selectionChanged,...
                'Bindings',{obj 'motorList' 'choices'},...
                'Position', [46 ph-97 190 49]);
            
            uicontrol('parent', obj.hPanel, ...
                'string','Add New',...
                'Units', 'pixels', ...
                'Position', [46 ph-132 74 28], ...
                'callback',@obj.addNew);
            
            obj.hRemove = uicontrol('parent', obj.hPanel, ...
                'string','Remove Selected',...
                'Units', 'pixels', ...
                'Position', [126 ph-132 110 28], ...
                'callback',@obj.removeSelected);
        
            mph = 565;
            mpw = 780;
            obj.hMotorPanel = uipanel( ...
                'parent', obj.hPanel, ...
                'Units', 'pixels', ...
                'fontsize',10,...
                'Position', [46 ph-164-mph mpw mph]);
            
            uicontrol( ...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Configure connection settings for the selected motor stage controller.', ...  
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'fontsize',10,...
                'Position', [46 mph-54 676 16]);
            
            obj.hNoSelText = uicontrol( ...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Add or select a motor controller above in order to configure it...', ...  
                'HorizontalAlignment', 'center', ...
                'FontSize',11,...
                'ForegroundColor',.5*ones(1,3),...
                'Units', 'pixels', ...
                'Visible','off',...
                'Position', [1 mph-56 mpw-2 30]);
            
            uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Controller Type', ...
                'TooltipString', '', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 mph-94 108 14]);
        
            most.gui.uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'popupmenu', ...
                'String', {'None'}, ...
                'TooltipString', '', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Bindings',{{obj 'mtrChoices' 'choices'} {obj 'controllerType' 'choice'}},...
                'Position', [206 mph-98 150 22]);
                
            uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Serial COM Port', ...
                'TooltipString', 'If using serial communication, enter COM Port for the controller.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 mph-134 108 14]);
            
            most.gui.popupMenuEdit(...
                'parent', obj.hMotorPanel, ...
                'Position', [206 mph-138 60 22],...
                'validationFunc',@obj.validateComChoice,...
                'Bindings',{{obj 'comPort' 'string'} {obj 'comChoices' 'choices'}});
            
            uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Additional Params (Optional)', ...
                'TooltipString', 'Some motor controllers take optional parameters. Specify these as property-value pairs.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 mph-174 148 14]);
        
            most.gui.paramCellArrayEdit(...
                'parent', obj.hMotorPanel, ...
                'TooltipString', 'Some motor controllers take optional parameters. Specify these as property-value pairs.', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'pixels', ...
                'ParameterOptions',{'baudRate' 'stageType' 'usbName'},...
                'Bindings',{{obj 'additionalParams'}},...
                'Position', [206 mph-178 150 22]);
            
            
            uicontrol( ...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Customize dimension parameters by selecting how physical motor dimensions are mapped to the ScanImage XYZ coordinate system. You can also invert motor dimensions and customize the position unit conversion.', ...  
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'fontsize',10,...
                'Position', [46 mph-240 676 32]);
            

            x = '<html><table border=0 width=75><TR><TD><center>1</center></TD></TR></table></html>';
            y = '<html><table border=0 width=75><TR><TD><center>2</center></TD></TR></table></html>';
            z = '<html><table border=0 width=75><TR><TD><center>3</center></TD></TR></table></html>';
            obj.hDimensionTable = uitable('parent', obj.hMotorPanel, ...
                'ColumnName', {'Physical|Dimension' 'ScanImage|Mapping' 'Invert' 'Conversion|(um/unit)'}, ...
                'Data',{x 'X' false []; y 'Y' false []; z 'Z' false [];},...
                'ColumnFormat', {'numeric', {' ' 'X' 'Y' 'Z'}, 'logical', 'numeric'}, ...
                'ColumnEditable', [false, true, true true], ...
                'ColumnWidth', {75, 75, 45 75}, ...
                'RowName', [],...
                'CellEditCallback',@obj.tblCb,...
                'Units', 'pixels', ...
                'Position', [46 mph-340 272 94]);
            
            
            uicontrol( ...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'For motors that support different move velocities, you can specify what velocity to use for short and long moves. The distance threshold for short and long moves can be specified later. (Optional)', ...  
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'fontsize',10,...
                'Position', [46 mph-410 676 32]);
            
            uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Short Move Velocity', ...
                'TooltipString', 'Velocity to use for short moves. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 mph-440 120 14]);
            
            most.gui.uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'edit', ...
                'String', '', ...
                'TooltipString', 'Enter the velocity to use for moves smaller than motorFastMotionThreshold value. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'pixels', ...
                'Bindings',{{obj 'shortVelocity' 'value'}},...
                'Position', [166 mph-445 60 22]);
            
            uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Long Move Velocity', ...
                'TooltipString', 'Enter the velocity to use for moves larger than motorFastMotionThreshold value. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [286 mph-440 120 14]);
        
            most.gui.uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'edit', ...
                'String', '', ...
                'TooltipString', 'Enter the velocity to use for moves larger than motorFastMotionThreshold value. If unspecified, default value used for controller. Specified in units appropriate to the controller type.', ...
                'HorizontalAlignment', 'center', ...
                'Bindings',{{obj 'longVelocity' 'value'}},...
                'Units', 'pixels', ...
                'Position', [406 mph-445 60 22]);
            
            uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Some motors report that a move has completed before the stage has settled. This can cause error in the reading of the position. This option adds delay from when the move has completed to when the position is read.', ...
                'HorizontalAlignment', 'left', ...
                'fontsize',10,...
                'Units', 'pixels', ...
                'Position', [46 mph-505 676 32]);
            
            uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'text', ...
                'String', 'Move Complete Delay (sec)', ...
                'TooltipString', '', ...
                'HorizontalAlignment', 'left', ...
                'Units', 'pixels', ...
                'Position', [46 mph-535 150 14]);
            
            most.gui.uicontrol(...
                'parent', obj.hMotorPanel, ...
                'Style', 'edit', ...
                'String', '0', ...
                'HorizontalAlignment', 'center', ...
                'Units', 'pixels', ...
                'Bindings',{{obj 'moveCompleteDelay' 'value'}},...
                'Position', [206 mph-540 50 22]);
            
            obj.reload();
        end
        
        function delete(obj)
        end
        
        function reload(obj)
            obj.mtrChoices = obj.hConfigEditor.motorName2RegMap.keys;
            obj.comChoices = [{'None'}; obj.hConfigEditor.availableComPorts];
            
            mdfData = obj.getCurrentMdfDataStruct();
            emps = arrayfun(@(s)isempty(s.controllerType),mdfData.motors);
            obj.motors = mdfData.motors(~emps);
            obj.updateMotorListNames();
            obj.hMotorList.Value = 1;
            obj.selectionChanged();
        end
        
        function s = getNewVarStruct(obj)
            s = obj.getCurrentMdfDataStruct();
            
            % if there used to be more motors than there are now, make sure
            % the controller is blanked on the extra entries
            s.motors = arrayfun(@(s)setfield(s, 'controllerType', ''),s.motors);
            
            s.motors(1:numel(obj.motors)) = obj.motors;
        end
    end
    
    methods
        function addNew(obj,varargin)
            obj.motors(end+1).controllerType = 'simulated.stage';
            obj.motors(end).customArgs = {};
            obj.motors(end).invertDim = '+++';
            obj.motors(end).dimensions = '';
            
            dims = [obj.motors.dimensions];
            obj.motors(end).dimensions = setdiff('XYZ',dims);
            
            obj.updateMotorListNames();
            obj.hMotorList.Value = numel(obj.motors);
            obj.selectionChanged();
        end
        
        function removeSelected(obj,varargin)
            v = obj.hMotorList.Value;
            if (v > 0) && (v <= numel(obj.motors))
                obj.motors(v) = [];
            end
            
            obj.updateMotorListNames();
            obj.hMotorList.Value = min(obj.hMotorList.Value,numel(obj.motorList));
            obj.selectionChanged();
        end
        
        function selectionChanged(obj,varargin)
            if isempty(obj.motorList)
                obj.hMotorPanel.Title = '';
                obj.hMotorList.Value = 1;
                set(obj.hMotorPanel.Children, 'visible', 'off');
                obj.hNoSelText.Visible = 'on';
                obj.hRemove.Enable = 'off';
            else
                v = obj.hMotorList.Value;
                
                obj.controllerType = obj.hConfigEditor.hMotorRegistry.getControllerInfo(obj.motors(v).controllerType).ListName;
                
                comP = obj.motors(v).comPort;
                if isempty(comP)
                    obj.comPort = 'None';
                elseif isnumeric(comP)
                    obj.comPort = sprintf('COM%d',comP);
                else
                    obj.comPort = comP;
                end
                
                obj.additionalParams = obj.motors(v).customArgs;
                
                newDat = {'' false []; '' false []; '' false [];};
                
                N = min(3,numel(obj.motors(v).dimensions));
                newDat(1:N,1) = arrayfun(@(x){strrep(x,'-','')},obj.motors(v).dimensions(1:N))';
                
                N = min(3,numel(obj.motors(v).invertDim));
                newDat(1:N,2) = arrayfun(@(x){x=='-'},obj.motors(v).invertDim(1:N))';
                
                N = min(3,numel(obj.motors(v).positionDeviceUnits));
                newDat(1:N,3) = num2cell(obj.motors(v).positionDeviceUnits(1:N))';
                
                obj.hDimensionTable.Data(:,2:end) = newDat;
                
                obj.shortVelocity = obj.motors(v).velocitySlow;
                obj.longVelocity = obj.motors(v).velocityFast;
                
                if isempty(obj.motors(v).moveCompleteDelay)
                    obj.moveCompleteDelay = 0;
                else
                    obj.moveCompleteDelay = obj.motors(v).moveCompleteDelay;
                end
                
                obj.hMotorPanel.Title = ['Motor Settings: ' obj.motorList{v}];
                set(obj.hMotorPanel.Children, 'visible', 'on');
                obj.hNoSelText.Visible = 'off';
                obj.hRemove.Enable = 'on';
            end
        end
        
        function [lvl,v,errMsg] = validateComChoice(obj,v,~)
            errMsg = '';
            if all(isstrprop(v, 'digit'))
                v = ['COM' v];
            elseif strncmpi(v,'com',3) && (length(v) > 3) && all(isstrprop(v(4:end), 'digit'))
                v(1:3) = 'COM';
            else
                if strcmp(v,'None')
                    lvl = 0;
                else
                    lvl = 2;
                    errMsg = 'Must be a numeric COM port ID.';
                end
                return;
            end
            
            if ismember(v,obj.comChoices)
                lvl = 0;
            else
                lvl = 1;
                errMsg = 'COM port not found. If ScanImage is running, this could be because the port is currently open.';
            end
        end
        
        function updateMotorListNames(obj)
            if isempty(obj.motors)
                obj.motorList = {};
            else
                names = {obj.motors.controllerType};
                dat = cellfun(@(x)obj.hConfigEditor.hMotorRegistry.getControllerInfo(x),names);
                obj.motorList = arrayfun(@(rd,d){[rd.ListName ' (' strrep(d.dimensions,'-','') ')']},dat,obj.motors);
            end
        end
        
        function tblCb(obj,src,~)
            idx = obj.hMotorList.Value;
            
            dims = strtrim(src.Data(:,2)');
            dims(cellfun(@isempty,dims)) = {'-'};
            obj.motors(idx).dimensions = [dims{:}];
            
            obj.motors(idx).invertDim = '+++';
            obj.motors(idx).invertDim([src.Data{:,3}]) = '-';
            
            un = src.Data(:,4);
            un(cellfun(@isempty,un)) = {nan};
            un = [un{:}];
            if all(isnan(un))
                obj.motors(idx).positionDeviceUnits = [];
                src.Data(:,4) = {[]};
            else
                obj.motors(idx).positionDeviceUnits = un;
                src.Data(:,4) = num2cell(un)';
            end
            
            obj.updateMotorListNames();
        end
    end
    
    %% Prop access
    methods
        function set.controllerType(obj,v)
            obj.controllerType = v;
            
            idx = obj.hMotorList.Value;
            obj.motors(idx).controllerType = obj.hConfigEditor.motorName2RegMap(v);
            obj.updateMotorListNames();
        end
        
        function set.comPort(obj,v)
            obj.comPort = v;
            
            idx = obj.hMotorList.Value;
            
            if strcmp(v,'None')
                obj.motors(idx).comPort = [];
            elseif strncmpi(v,'com',3) && (length(v) > 3) && all(isstrprop(v(4:end), 'digit'))
                obj.motors(idx).comPort = str2double(v(4:end));
            else
                obj.motors(idx).comPort = v;
            end
        end
        
        function set.additionalParams(obj,v)
            obj.additionalParams = v;
            
            idx = obj.hMotorList.Value;
            obj.motors(idx).customArgs = v;
        end
        
        function set.shortVelocity(obj,v)
            v(isnan(v)) = [];
            obj.shortVelocity = v;
            
            idx = obj.hMotorList.Value;
            obj.motors(idx).velocitySlow = v;
        end
        
        function set.longVelocity(obj,v)
            v(isnan(v)) = [];
            obj.longVelocity = v;
            
            idx = obj.hMotorList.Value;
            obj.motors(idx).velocityFast = v;
        end
        
        function set.moveCompleteDelay(obj,v)
            v(isnan(v)) = 0;
            obj.moveCompleteDelay = v;
            
            idx = obj.hMotorList.Value;
            obj.motors(idx).moveCompleteDelay = v;
        end
    end
end


%--------------------------------------------------------------------------%
% MotorsPage.m                                                             %
% Copyright © 2018 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage is licensed under the Apache License, Version 2.0              %
% (the "License"); you may not use any files contained within the          %
% ScanImage release  except in compliance with the License.                %
% You may obtain a copy of the License at                                  %
% http://www.apache.org/licenses/LICENSE-2.0                               %
%                                                                          %
% Unless required by applicable law or agreed to in writing, software      %
% distributed under the License is distributed on an "AS IS" BASIS,        %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. %
% See the License for the specific language governing permissions and      %
% limitations under the License.                                           %
%--------------------------------------------------------------------------%
