function [methodinfo,structs,enuminfo,ThunkLibName]=pointerHandling
%POINTERHANDLING Create structures to define interfaces found in 'pointerHandling'.

%This function was generated by loadlibrary.m parser version  on Fri Apr  7 16:14:11 2017
%perl options:'pointerHandling.i -outfile=pointerHandling.m -thunkfile=pointerHandling_thunk_pcwin64.c -header=pointerHandling.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'pointerHandling_thunk_pcwin64');
% void libPointerToUint64 ( void * myPointer , uint64_t * uint64Pointer ); 
fcns.thunkname{fcnNum}='voidvoidPtrvoidPtrThunk';fcns.name{fcnNum}='libPointerToUint64'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'voidPtr', 'uint64Ptr'};fcnNum=fcnNum+1;
% void * uint64ToLibPointer ( uint64_t * uint64Pointer ); 
fcns.thunkname{fcnNum}='voidPtrvoidPtrThunk';fcns.name{fcnNum}='uint64ToLibPointer'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='voidPtr'; fcns.RHS{fcnNum}={'uint64Ptr'};fcnNum=fcnNum+1;
methodinfo=fcns;

%--------------------------------------------------------------------------%
% pointerHandling.m                                                        %
% Copyright © 2018 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage is licensed under the Apache License, Version 2.0              %
% (the "License"); you may not use any files contained within the          %
% ScanImage release  except in compliance with the License.                %
% You may obtain a copy of the License at                                  %
% http://www.apache.org/licenses/LICENSE-2.0                               %
%                                                                          %
% Unless required by applicable law or agreed to in writing, software      %
% distributed under the License is distributed on an "AS IS" BASIS,        %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. %
% See the License for the specific language governing permissions and      %
% limitations under the License.                                           %
%--------------------------------------------------------------------------%
