function h1 = cycleModeControlsV5_fig(policy,visibility,hController)
% --- Creates and returns a handle to the GUI figure. 
% policy - create a new figure or use a singleton. 'new' or 'reuse'.
% visibility - either 'on' or 'off'
% hController - handle to cycle-mode controller

    persistent hsingleton;
    if strcmpi(policy, 'reuse') & ishandle(hsingleton)
        h1 = hsingleton;
        return;
    end

    handles.hController = hController;

    appdata = [];
    appdata.GUIDEOptions = struct(...
        'active_h', [], ...
        'taginfo', struct(...
        'figure', 2, ...
        'uitable', 2, ...
        'checkbox', 6, ...
        'pushbutton', 19, ...
        'text', 9, ...
        'edit', 9, ...
        'slider', 2, ...
        'uipanel', 2), ...
        'override', 0, ...
        'release', 13, ...
        'resize', 'none', ...
        'accessibility', 'callback', ...
        'mfile', 1, ...
        'callbacks', 1, ...
        'singleton', 1, ...
        'syscolorfig', 1, ...
        'blocking', 0, ...
        'lastSavedFile', '', ...
        'lastFilename', '');
        %'lastSavedFile', 'C:\code\cycleMode\cycleModeControlsV5_fig.m', ...
        %'lastFilename', 'C:\code\scanimage_3_8_1\ScanImage\guis\gui_building\cycleGUI.fig');
    appdata.lastValidTag = 'figure1';
    appdata.GUIDELayoutEditor = [];
    appdata.initTags = struct(...
        'handle', [], ...
        'tag', 'figure1');

    h1 = figure(...
    'Units','characters',...
    'Position',[103.8 39.3076923076923 41.5 23.2],...
    'Visible',visibility,...
    'Color',get(0,'defaultUIControlBackgroundColor'),...
    'IntegerHandle','off',...
    'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
    'MenuBar','none',...
    'Name','CYCLE-MODE CONTROLS',...
    'NumberTitle','off',...
    'Resize','off',...
    'PaperPosition',get(0,'defaultfigurePaperPosition'),...
    'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
    'HandleVisibility','callback',...
    'Tag','figure1',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata},...
    'CloseRequestFcn',{@closeCycleGUI});

    handles.output = h1;

    appdata = [];
    appdata.lastValidTag = 'tblCycle';

    %'Data',{  blanks(0) [] 'Posn #' blanks(0) [] [] [] [] [] blanks(0) [] [] []; blanks(0) [] 'Posn #' blanks(0) [] [] [] [] [] blanks(0) [] [] [] },...
    %'ColumnFormat',{  'char' 'numeric' {  'Posn #' 'ROI #' 'Step' } 'char' 'numeric' 'numeric' 'numeric' 'numeric' 'numeric' 'char' 'numeric' 'numeric' 'logical' },...
    handles.tblCycle = uitable(...
    'Parent',h1,...
    'Units','characters',...
    'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
    'ColumnName',{  'Config|Name'; 'Iteration|Delay'; 'Motor|Action'; 'Motor Step/|Posn #/ROI #'; 'Repeat|Period'; '#|Repeats'; '#|Slices'; 'Z Step|/Slice'; '#|Frames'; 'Power'; '# Avg|Frames'; 'Frames|/File'; 'Lock|Frames/File' },...
    'ColumnWidth',{  80 50 75 75 45 45 45 45 45 60 45 45 75 },...
    'Position',[42 2.61538461538462 152.2 18],...
    'ColumnEditable',logical([0 1 1 1 1 1 1 1 1 1 1 1 1]),...
    'ColumnFormat',{  'char' 'numeric' {  'Posn #' 'ID #' } 'char' 'numeric' 'numeric' 'numeric' 'numeric' 'numeric' 'char' 'numeric' 'numeric' 'logical' },...
    'CellEditCallback',@(hObject,eventdata)tblCycleCellEdit_Callback(hObject,eventdata,guidata(hObject)),...
    'CellSelectionCallback',@(hObject,eventdata)tblCycleCellSelect_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Enter cycle info: each row represents a single cycle iteration.',...
    'Tag','tblCycle',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );
    %'KeyPressFcn',@(hObject,eventdata)tblCycle_KeyPressFcn(hObject,eventdata,guidata(hObject)),...

    appdata = [];
    appdata.lastValidTag = 'cbApplyToAll';

    %'Callback',@(hObject,eventdata)cbApplyToAll_Callback(hObject,eventdata,guidata(hObject)),...
    handles.cbApplyToAll = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Apply To All',...
    'Style','checkbox',...
    'Position',[81.6000000000003 0.384615384615511 17.4 1.76923076923077],...
    'Visible', 'off',...
    'Children',[],...
    'Enable','on',...
    'TooltipString','If selected, any cell edit will be applied to all other cells in that column.',...
    'Tag','cbApplyToAll',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'cbCycleOn';

    %'Callback',@(hObject,eventdata)cycleModeControlsV5_fig('cbCycleOn_Callback',hObject,eventdata,guidata(hObject)),...
    %'Callback',@(hObject,eventdata)cbCycleOn_Callback(hObject,eventdata,guidata(hObject)),...
    %'Callback',@cbCycleOn_Callback,...
    handles.cbCycleOn = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Cycle Mode On',...
    'Style','checkbox',...
    'Position',[1.2 21.0000000000001 20.6 1.76923076923077],...
    'Callback',@(hObject,eventdata)cbCycleOn_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'TooltipString','Selects if Cycle Mode is on or off.',...
    'Tag','cbCycleOn',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


    appdata = [];
    appdata.lastValidTag = 'pbAddRow';

    handles.pbAddRow = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Add Iteration',...
    'Position',[64.2 20.9230769230769 19.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)pbAddRow_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Adds an additional row to the table.',...
    'Tag','pbAddRow',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'pbDropRow';

    handles.pbDropRow = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Remove Iteration',...
    'Position',[84.2000000000001 20.9230769230769 19.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)pbDropRow_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Removes the selected row.',...
    'Tag','pbDropRow',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'pbClearTable';

    handles.pbClearTable = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Clear All',...
    'Position',[142.8 20.923076923077 10 1.76923076923077],...
    'Callback',@(hObject,eventdata)pbClearTable_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Clears the contents of the table.',...
    'Tag','pbClearTable',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'cyclePanel';

    handles.cyclePanel = uipanel(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuipanelFontUnits'),...
    'Units','pixels',...
    'Title',blanks(0),...
    'Position',[6 35 200 234],...
    'Clipping','off',...
    'Tag','cyclePanel',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'lbCycleName';

    handles.lbCycleName = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Cycle Name',...
    'Style','text',...
    'Position',[3 16.0769230769231 12.8 1.07692307692308],...
    'Children',[],...
    'Enable','on',...
    'Tag','lbCycleName',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'etCycleName';

    handles.etCycleName = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'Style','edit',...
    'Position',[16 15.7692307692308 22.2 1.53846153846154],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)etCycleName_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Displays the current cycle name.',...
    'Tag','etCycleName',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'lbCycleIter';

    handles.lbCycleIter = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'HorizontalAlignment','left',...
    'ListboxTop',0,...
    'String','Cycle Iters Done',...
    'Style','text',...
    'Position',[1.2 8.23076923076924 18.2 1.15384615384615],...
    'Children',[],...
    'Enable','on',...
    'Tag','lbCycleIter',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'etCycleIteration';

    handles.etCycleIteration = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String',blanks(0),...
    'Style','edit',...
    'Position',[18 8.00000000000003 8 1.46153846153846],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)etCycleIteration_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','inactive',...
    'TooltipString','The current cycle iteration index.',...
    'Tag','etCycleIteration',...
    'FontWeight','bold',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'etCycleLength';

    handles.etCycleLength = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String',blanks(0),...
    'Style','edit',...
    'Position',[30.2 8.00000000000001 8 1.46153846153846],...
    'BackgroundColor',[1 1 1],...
    'Children',[],...
    'Enable','inactive',...
    'TooltipString','The total number of cycle iterations.',...
    'Tag','etCycleLength',...
    'FontWeight','bold',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'lbOf';

    handles.lbOf = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String','of',...
    'Style','text',...
    'Position',[26.4 8.00000000000001 3.2 1.38461538461539],...
    'Children',[],...
    'Enable','on',...
    'Tag','lbOf',...
    'FontSize',10,...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'lbCyclesDone';

    %'HorizontalAlignment','right',...
    handles.lbCyclesDone = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String','Cycles Done',...
    'Style','text',...
    'Position',[5 11.6153846153846 12.8 1.46153846153846],...
    'Children',[],...
    'Enable','on',...
    'Tag','lbCyclesDone',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'etCycleCount';

    handles.etCycleCount = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String',blanks(0),...
    'Style','edit',...
    'Position',[18 11.6923076923077 8 1.46153846153846],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)etCycleCount_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','inactive',...
    'TooltipString','The number of completed cycle repeats.',...
    'Tag','etCycleCount',...
    'FontWeight','bold',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'etNumCycleRepeats';

    handles.etNumCycleRepeats = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String',blanks(0),...
    'Style','edit',...
    'Position',[30.2 11.6923076923077 8 1.46153846153846],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)etNumCycleRepeats_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','The total number of cycle repeats.',...
    'Tag','etNumCycleRepeats',...
    'FontWeight','bold',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'lbOf2';

    handles.lbOf2 = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String','of',...
    'Style','text',...
    'Position',[26.4 11.6923076923077 3.2 1.38461538461539],...
    'Children',[],...
    'Enable','on',...
    'Tag','lbOff2',...
    'FontSize',10,...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    %appdata = [];
    %appdata.lastValidTag = 'pbCycleIterationDec';

    %handles.pbCycleIterationDec = uicontrol(...
    %'Parent',handles.cyclePanel,...
    %'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    %'Units','characters',...
    %'String','<',...
    %'Position',[18 6.3846153846154 3.6 1.38461538461539],...
    %'Callback',@(hObject,eventdata)pbCycleIterationDec_Callback(hObject,eventdata,guidata(hObject)),...
    %'Children',[],...
    %'Enable','off',...
    %'TooltipString','Decrements the current cycle iteration.',...
    %'Tag','pbCycleIterationDec',...
    %'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    %appdata = [];
    %appdata.lastValidTag = 'pbCycleIterationInc';

    %handles.pbCycleIterationInc = uicontrol(...
    %'Parent',handles.cyclePanel,...
    %'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    %'Units','characters',...
    %'String','>',...
    %'Position',[22 6.3846153846154 3.6 1.38461538461539],...
    %'Callback',@(hObject,eventdata)pbCycleIterationInc_Callback(hObject,eventdata,guidata(hObject)),...
    %'Children',[],...
    %'Enable','off',...
    %'TooltipString','Increments the current cycle iteration.',...
    %'Tag','pbCycleIterationInc',...
    %'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'pbSave';

    handles.pbSave = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Save',...
    'Position',[31 13.6923076923077 7.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)pbSave_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Saves the current cycle parameters to a .CYC file.',...
    'Tag','pbSave',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'pbLoad';

    handles.pbLoad = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Load',...
    'Position',[22 13.6923076923077 7.6 1.76923076923077],...
    'Callback',@(hObject,eventdata)pbLoad_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Loads a .CYC file.',...
    'Tag','pbLoad',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'cbGoHomeAtCycleEnd';

    handles.cbGoHomeAtCycleEnd = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Go home at cycle end',...
    'Style','checkbox',...
    'Position',[0.8 4.61538461538464 25 1.76923076923077],...
    'Callback',@(hObject,eventdata)cbGoHomeAtCycleEnd_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Returns the stage to the home position after the completion of a cycle.',...
    'Tag','cbGoHomeAtCycleEnd',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'cbRestoreOriginalCFG';

    handles.cbRestoreOriginalCFG = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Restore original CFG',...
    'Style','checkbox',...
    'Position',[0.8 3.23076923076923 25 1.76923076923077],...
    'Callback',@(hObject,eventdata)cbRestoreOriginalCFG_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','If selected, the original configuration will be loaded after the cycle is complete.',...
    'Tag','cbRestoreOriginalCFG',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'cbCycleAutoReset';

    handles.cbCycleAutoReset = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Auto-reset Iteration/Count',...
    'Style','checkbox',...
    'Position',[0.8 1.75 28.6 1.76923076923077],...
    'Callback',@(hObject,eventdata)cbCycleAutoReset_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','If selected, the cycle count/iteration will be reset at the beginning of a new cycle.',...
    'Tag','cbCycleAutoReset',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'pbCycleReset';

    handles.pbCycleReset = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Reset',...
    'Position',[31 2 7.6 1.38461538461538],...
    'Callback',@(hObject,eventdata)pbCycleReset_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Resets the current cycle count/iteration.',...
    'Tag','pbCycleReset',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    %appdata = [];
    %appdata.lastValidTag = 'pbCycleCountDec';

    %handles.pbCycleCountDec = uicontrol(...
    %'Parent',handles.cyclePanel,...
    %'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    %'Units','characters',...
    %'String','<',...
    %'Position',[18 10.0769230769231 3.6 1.38461538461539],...
    %'Callback',@(hObject,eventdata)pbCycleCountDec_Callback(hObject,eventdata,guidata(hObject)),...
    %'Children',[],...
    %'Enable','off',...
    %'TooltipString','Decrements the cycle counter.',...
    %'Tag','pbCycleCountDec',...
    %'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    %appdata = [];
    %appdata.lastValidTag = 'pbCycleCountInc';

    %handles.pbCycleCountInc = uicontrol(...
    %'Parent',handles.cyclePanel,...
    %'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    %'Units','characters',...
    %'String','>',...
    %'Position',[22 10.0769230769231 3.6 1.38461538461539],...
    %'Callback',@(hObject,eventdata)pbCycleCountInc_Callback(hObject,eventdata,guidata(hObject)),...
    %'Children',[],...
    %'Enable','off',...
    %'TooltipString','Increments the cycle counter.',...
    %'Tag','pbCycleCountInc',...
    %'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'lbIterationsPerLoop';

    handles.lbIterationsPerLoop = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','# Iterations per LOOP',...
    'Style','text',...
    'Visible', 'off',...
    'Position',[10.6 0.446153846153847 21.6 1.07692307692308],...
    'Children',[],...
    'Enable','on',...
    'Tag','lbIterationsPerLoop',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'etIterationsPerLoop';

    handles.etIterationsPerLoop = uicontrol(...
    'Parent',handles.cyclePanel,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'ListboxTop',0,...
    'String',blanks(0),...
    'Style','edit',...
    'Visible', 'off',...
    'Position',[1.00000000000001 0.307692307692311 9 1.46153846153846],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)etIterationsPerLoop_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','The number of iterations to be executed each time LOOP is pressed.',...
    'Tag','etIterationsPerLoop',...
    'FontWeight','bold',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'tbShowAdvanced';

    handles.tbShowAdvanced = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','>>',...
    'Style','togglebutton',...
    'Position',[35.8000000000001 0.46153846153847 5 1.76923076923077],...
    'Callback',@(hObject,eventdata)tbShowAdvanced_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Shows advanced cycle parameters.',...
    'Tag','tbShowAdvanced',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    %appdata = [];
    %appdata.lastValidTag = 'pbMetaStack';

    %h32 = uicontrol(...
    %'Parent',h1,...
    %'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    %'Units','characters',...
    %'String','Meta-Stack',...
    %'Position',[139 0.46153846153847 13.8 1.76923076923077],...
    %'Callback',@(hObject,eventdata)cycleModeControlsV5_fig('pbMetaStack_Callback',hObject,eventdata,guidata(hObject)),...
    %'Children',[],...
    %'Enable','off',...
    %'TooltipString','Opens the Meta-stack macro dialog.',...
    %'Tag','pbMetaStack',...
    %'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    %appdata = [];
    %appdata.lastValidTag = 'pbMosaic';

    %h33 = uicontrol(...
    %'Parent',h1,...
    %'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    %'Units','characters',...
    %'String','Mosaic',...
    %'Position',[124.4 0.46153846153847 13.8 1.76923076923077],...
    %'Callback',@(hObject,eventdata)cycleModeControlsV5_fig('pbMosaic_Callback',hObject,eventdata,guidata(hObject)),...
    %'Children',[],...
    %'Enable','off',...
    %'TooltipString','Opens the Mosaic macro dialog.',...
    %'Tag','pbMosaic',...
    %'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'pbAdd';

    handles.pbAdd = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Add CFG...',...
    'Position',[48.4 0.461538461538478 15.8 1.76923076923077],...
    'Callback',@(hObject,eventdata)pbAdd_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Adds a config file in the selected cell(s).',...
    'Tag','pbAdd',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'pbClear';

    handles.pbClear = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Clear',...
    'Position',[70.8000000000003 0.461538461538462 9.8 1.76923076923077],...
    'Callback',@(hObject,eventdata)pbClear_Callback(hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Enable','on',...
    'TooltipString','Clears the contents of the selected cell(s).',...
    'Tag','pbClear',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'lbCycleIterData';

    handles.lbCycleIterData = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Cycle Iteration Data',...
    'Style','text',...
    'Position',[42 21.2307692307692 19.4 1.07692307692308],...
    'Children',[],...
    'Tag','lbCycleIterData',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    hsingleton = h1;

    guidata(h1, handles);

    function closeCycleGUI(hObject,eventdata,handles)
        % We just wish to hide the GUI, closing should be delegated to the controller
        set(hObject,'Visible', 'off');
        return;
    end

    % --- Set application data first then calling the CreateFcn. 
    function local_CreateFcn(hObject, eventdata, createfcn, appdata)
        if ~isempty(appdata)
           names = fieldnames(appdata);
           for i=1:length(names)
               name = char(names(i));
               setappdata(hObject, name, getfield(appdata,name));
           end
        end

        if ~isempty(createfcn)
           if isa(createfcn,'function_handle')
               createfcn(hObject, eventdata);
           else
               eval(createfcn);
           end
        end
    end

    % CALLBACKS (to controller)

    function tblCycleCellEdit_Callback(hObject, eventdata, handles)
        handles.hController.setCellContents(get(hObject, 'Data'),eventdata);
    end

    function tblCycleCellSelect_Callback(hObject, eventdata, handles)
        handles.hController.selectCell(eventdata);
    end

    function cbApplyToAll_Callback(hObject, eventdata, handles)
        handles.hController.setApplyToAllMode(get(hObject, 'Value'));
    end

    function cbCycleOn_Callback(hObject, eventdata, handles)
        handles.hController.setCycleEnabledMode(get(hObject, 'Value'));
    end

    function pbAddRow_Callback(hObject, eventdata, handles)
        handles.hController.addRow;
    end

    function pbDropRow_Callback(hObject, eventdata, handles)
        handles.hController.dropRow;
    end

    function pbClearTable_Callback(hObject, eventdata, handles)
        handles.hController.clearTable;
    end

    function etCycleName_Callback(hObject, eventdata, handles)
        handles.hController.setCycleName(get(hObject, 'String'));
    end

    function etCycleIteration_Callback(hObject, eventdata, handles)
        handles.hController.setCurrentCycleIterationIndex;
    end

    function etCycleCount_Callback(hObject, eventdata, handles)
        % NOT USER EDITABLE
        %handles.hController.setCompletedCycleRepeats;
    end

    function etNumCycleRepeats_Callback(hObject, eventdata, handles)
        handles.hController.setTotalCycleRepeats(get(hObject, 'String'));
    end

    %function pbCycleIterationDec_Callback(hObject, eventdata, handles)
        %handles.hController.decrementCycleIterations;
    %end

    %function pbCycleIterationInc_Callback(hObject, eventdata, handles)
        %handles.hController.incrementCycleIterations;
    %end

    function pbSave_Callback(hObject, eventdata, handles)
        handles.hController.saveCycle;
    end

    function pbLoad_Callback(hObject, eventdata, handles)
        handles.hController.loadCycle;
    end

    function cbGoHomeAtCycleEnd_Callback(hObject, eventdata, handles)
        handles.hController.goHomeAtCycleEndModeChanged(get(hObject, 'Value'));
    end

    function cbRestoreOriginalCFG_Callback(hObject, eventdata, handles)
        handles.hController.restoreOriginalCFGChanged(get(hObject, 'Value'));
    end

    function cbCycleAutoReset_Callback(hObject, eventdata, handles)
        handles.hController.autoResetModeChanged(get(hObject, 'Value'));
    end

    function pbCycleReset_Callback(hObject, eventdata, handles)
        handles.hController.resetCycle;
    end

    %function pbCycleCountDec_Callback(hObject, eventdata, handles)
        %handles.hController.decrementCycleCount;
    %end

    %function pbCycleCountInc_Callback(hObject, eventdata, handles)
        %handles.hController.incrementCycleCount;
    %end

    function etIterationsPerLoop_Callback(hObject, eventdata, handles)
    end

    function tbShowAdvanced_Callback(hObject, eventdata, handles)
        handles.hController.toggleShowAdvancedParameters;
    end

    function pbAdd_Callback(hObject, eventdata, handles)
        handles.hController.addCFG;
    end

    function pbClear_Callback(hObject, eventdata, handles)
        handles.hController.clearSelectedCellContents;
    end
end


%--------------------------------------------------------------------------%
% cycleModeControlsV5_fig.m                                                %
% Copyright © 2018 Vidrio Technologies, LLC                                %
%                                                                          %
% ScanImage is licensed under the Apache License, Version 2.0              %
% (the "License"); you may not use any files contained within the          %
% ScanImage release  except in compliance with the License.                %
% You may obtain a copy of the License at                                  %
% http://www.apache.org/licenses/LICENSE-2.0                               %
%                                                                          %
% Unless required by applicable law or agreed to in writing, software      %
% distributed under the License is distributed on an "AS IS" BASIS,        %
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. %
% See the License for the specific language governing permissions and      %
% limitations under the License.                                           %
%--------------------------------------------------------------------------%
